version: '3.8'

services:
  db:
    image: postgres:13
    container_name: investTrack_db
    environment:
      POSTGRES_DB: invest_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - investTrack_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    image: invest-tracker:2.0
    container_name: investTrack_app
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/invest_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - investTrack_network

networks:
  investTrack_network:
    driver: bridge


