version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: invest_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"

  app:
    image: invest-tracker:2.0
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/invest_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

